# Generated by Django 4.2.2 on 2023-11-08 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_new_app', '0002_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
